name: lint-push
on: push
jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: build brain games
        run: make build
      - name: run linter
        run: make lint